export type TCountryTypes = {
    id: number;
    countryName: string;
    countryCode: string;
    countryShortForm: string;
};
export const countries: TCountryTypes[] = [
    {
        id: 1,
        countryName: 'Afghanistan',
        countryCode: '+93',
        countryShortForm: 'AF',
    },
    {
        id: 2,
        countryName: 'Albania',
        countryCode: '+355',
        countryShortForm: 'AL',
    },
    {
        id: 3,
        countryName: 'Algeria',
        countryCode: '+213',
        countryShortForm: 'DZ',
    },
    {
        id: 4,
        countryName: 'Andorra',
        countryCode: '+376',
        countryShortForm: 'AD',
    },
    {
        id: 5,
        countryName: 'Angola',
        countryCode: '+244',
        countryShortForm: 'AO',
    },
    {
        id: 6,
        countryName: 'Argentina',
        countryCode: '+54',
        countryShortForm: 'AR',
    },
    {
        id: 7,
        countryName: 'Armenia',
        countryCode: '+374',
        countryShortForm: 'AM',
    },
    {
        id: 8,
        countryName: 'Australia',
        countryCode: '+61',
        countryShortForm: 'AU',
    },
    {
        id: 9,
        countryName: 'Austria',
        countryCode: '+43',
        countryShortForm: 'AT',
    },
    {
        id: 10,
        countryName: 'Azerbaijan',
        countryCode: '+994',
        countryShortForm: 'AZ',
    },
    {
        id: 11,
        countryName: 'Bahamas',
        countryCode: '+1-242',
        countryShortForm: 'BS',
    },
    {
        id: 12,
        countryName: 'Bahrain',
        countryCode: '+973',
        countryShortForm: 'BH',
    },
    {
        id: 13,
        countryName: 'Bangladesh',
        countryCode: '+880',
        countryShortForm: 'BD',
    },
    {
        id: 14,
        countryName: 'Barbados',
        countryCode: '+1-246',
        countryShortForm: 'BB',
    },
    {
        id: 15,
        countryName: 'Belarus',
        countryCode: '+375',
        countryShortForm: 'BY',
    },
    {
        id: 16,
        countryName: 'Belgium',
        countryCode: '+32',
        countryShortForm: 'BE',
    },
    {
        id: 17,
        countryName: 'Belize',
        countryCode: '+501',
        countryShortForm: 'BZ',
    },
    {
        id: 18,
        countryName: 'Benin',
        countryCode: '+229',
        countryShortForm: 'BJ',
    },
    {
        id: 19,
        countryName: 'Bhutan',
        countryCode: '+975',
        countryShortForm: 'BT',
    },
    {
        id: 20,
        countryName: 'Bolivia',
        countryCode: '+591',
        countryShortForm: 'BO',
    },
    {
        id: 21,
        countryName: 'Bosnia and Herzegovina',
        countryCode: '+387',
        countryShortForm: 'BA',
    },
    {
        id: 22,
        countryName: 'Botswana',
        countryCode: '+267',
        countryShortForm: 'BW',
    },
    {
        id: 23,
        countryName: 'Brazil',
        countryCode: '+55',
        countryShortForm: 'BR',
    },
    {
        id: 24,
        countryName: 'Brunei',
        countryCode: '+673',
        countryShortForm: 'BN',
    },
    {
        id: 25,
        countryName: 'Bulgaria',
        countryCode: '+359',
        countryShortForm: 'BG',
    },
    {
        id: 26,
        countryName: 'Burkina Faso',
        countryCode: '+226',
        countryShortForm: 'BF',
    },
    {
        id: 27,
        countryName: 'Burundi',
        countryCode: '+257',
        countryShortForm: 'BI',
    },
    {
        id: 28,
        countryName: 'Cambodia',
        countryCode: '+855',
        countryShortForm: 'KH',
    },
    {
        id: 29,
        countryName: 'Cameroon',
        countryCode: '+237',
        countryShortForm: 'CM',
    },
    {
        id: 30,
        countryName: 'Canada',
        countryCode: '+1',
        countryShortForm: 'CA',
    },
    {
        id: 31,
        countryName: 'Cape Verde',
        countryCode: '+238',
        countryShortForm: 'CV',
    },
    {
        id: 32,
        countryName: 'Central African Republic',
        countryCode: '+236',
        countryShortForm: 'CF',
    },
    {
        id: 33,
        countryName: 'Chad',
        countryCode: '+235',
        countryShortForm: 'TD',
    },
    {
        id: 34,
        countryName: 'Chile',
        countryCode: '+56',
        countryShortForm: 'CL',
    },
    {
        id: 35,
        countryName: 'China',
        countryCode: '+86',
        countryShortForm: 'CN',
    },
    {
        id: 36,
        countryName: 'Colombia',
        countryCode: '+57',
        countryShortForm: 'CO',
    },
    {
        id: 37,
        countryName: 'Comoros',
        countryCode: '+269',
        countryShortForm: 'KM',
    },
    {
        id: 38,
        countryName: 'Congo (Brazzaville)',
        countryCode: '+242',
        countryShortForm: 'CG',
    },
    {
        id: 39,
        countryName: 'Congo (Kinshasa)',
        countryCode: '+243',
        countryShortForm: 'CD',
    },
    {
        id: 40,
        countryName: 'Costa Rica',
        countryCode: '+506',
        countryShortForm: 'CR',
    },
    {
        id: 41,
        countryName: 'Croatia',
        countryCode: '+385',
        countryShortForm: 'HR',
    },
    { id: 42, countryName: 'Cuba', countryCode: '+53', countryShortForm: 'CU' },
    {
        id: 43,
        countryName: 'Cyprus',
        countryCode: '+357',
        countryShortForm: 'CY',
    },
    {
        id: 44,
        countryName: 'Czech Republic',
        countryCode: '+420',
        countryShortForm: 'CZ',
    },
    {
        id: 45,
        countryName: 'Denmark',
        countryCode: '+45',
        countryShortForm: 'DK',
    },
    {
        id: 46,
        countryName: 'Djibouti',
        countryCode: '+253',
        countryShortForm: 'DJ',
    },
    {
        id: 47,
        countryName: 'Dominica',
        countryCode: '+1-767',
        countryShortForm: 'DM',
    },
    {
        id: 48,
        countryName: 'Dominican Republic',
        countryCode: '+1-809',
        countryShortForm: 'DO',
    },
    {
        id: 49,
        countryName: 'Ecuador',
        countryCode: '+593',
        countryShortForm: 'EC',
    },
    {
        id: 50,
        countryName: 'Egypt',
        countryCode: '+20',
        countryShortForm: 'EG',
    },
];
